//
//  RegressionResults.h
//  KM
//
//  Created by Yang Yang on 9/6/10.
//  Copyright 2010 UCLA Molecular and Medical Pharmacology. All rights reserved.
//

#import <Cocoa/Cocoa.h>

// Class that stores results generated by KMDataProcessor
// Can be saved under KMResultDisplay, loaded from KMResultDisplay

@interface KMResults : NSObject <NSCoding> {
	NSString		*ModelName;
	NSMutableArray	*FittedParameters;
	//The array contains a mutable dictionary with a minimum of 5 elements:
	//YValues		- (array of yvalues for the fitted function)
	//XValues		- (array of xvalues for the fitted function)
	//WRSS			- Weighted Residuals Sum
	//VB			- Volume of Blood (since that is assumed to be the input function)
	//"Param Name"	- Fitted Value 
}

@property (retain) NSString *ModelName;
-(BOOL)addResult:(NSMutableDictionary *)entry;
-(BOOL)deleteResult:(int)index;
-(int)totalCount;
-(NSMutableDictionary*)entryForIndex:(int) i;
-(NSArray *)orderedArrayFor:(NSString *) something;
-(id)initWithModelName:(NSString *) model;
-(void)orderListBy:(NSString*)thiscategory;
@end
